"""
MAC address utilities for HotSpotchi.

Handles creation and formatting of MAC addresses that encode
Tamagotchi character identifiers.
"""

from hotspotchi.characters import Character

# MAC address prefix: locally administered unicast address
# The bytes 7A:6D:A0 are chosen to loosely spell "TAMA"
MAC_PREFIX = "02:7a:6d:a0"


def create_mac_address(character: Character) -> str:
    """Create a full MAC address encoding a character.

    The MAC address format is:
        02:7A:6D:A0:XX:YY

    Where:
        - 02 = locally administered unicast address
        - 7A:6D:A0 = "TAMA" signature
        - XX:YY = character identifier bytes

    Args:
        character: The character to encode

    Returns:
        MAC address string in xx:xx:xx:xx:xx:xx format
    """
    return f"{MAC_PREFIX}:{character.byte1:02x}:{character.byte2:02x}"


def format_mac(mac_str: str, uppercase: bool = True) -> str:
    """Format a MAC address string.

    Args:
        mac_str: MAC address to format
        uppercase: If True, convert to uppercase

    Returns:
        Formatted MAC address string
    """
    if uppercase:
        return mac_str.upper()
    return mac_str.lower()


def parse_mac_bytes(mac_str: str) -> tuple[int, int]:
    """Extract character bytes from a MAC address.

    Args:
        mac_str: MAC address in xx:xx:xx:xx:xx:xx format

    Returns:
        Tuple of (byte1, byte2) character identifier bytes

    Raises:
        ValueError: If MAC address format is invalid
    """
    parts = mac_str.split(":")
    if len(parts) != 6:
        raise ValueError(f"Invalid MAC address format: {mac_str}")

    try:
        byte1 = int(parts[-2], 16)
        byte2 = int(parts[-1], 16)
    except ValueError as e:
        raise ValueError(f"Invalid hex values in MAC address: {mac_str}") from e

    return byte1, byte2


def is_valid_mac(mac_str: str) -> bool:
    """Check if a string is a valid MAC address.

    Args:
        mac_str: String to validate

    Returns:
        True if valid MAC address format
    """
    try:
        parts = mac_str.split(":")
        if len(parts) != 6:
            return False
        for part in parts:
            if len(part) != 2:
                return False
            int(part, 16)  # Will raise if not valid hex
        return True
    except (ValueError, AttributeError):
        return False


def is_hotspotchi_mac(mac_str: str) -> bool:
    """Check if a MAC address was generated by HotSpotchi.

    Args:
        mac_str: MAC address to check

    Returns:
        True if MAC has the HotSpotchi prefix
    """
    return mac_str.lower().startswith(MAC_PREFIX.lower())
